### ISSUE TITLE
Request to be added

### ISSUE THREAD

**Issue by paulhendricks** [CrossChx/Lunch-Hackers#3]
@anglessteven I'd loved to be added to the list, thanks!

**Comment by paulhendricks** [comment]
@mattsteinpreis You should check this out too!

**Comment by stangles** [comment]
Hey @paulhendricks, sorry for taking so long to respond to this. This repository is no longer owned by CrossChx. All lunch hackers activities are now going to happen at my fork [here](https://github.com/anglessteven/Lunch-Hackers) going forward. Feel free to reopen your pull request there. Thanks for contributing and happy hacking!
